apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: personal-assistant-service
      port: 5000
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml